---
- name: Validar y modificar archivo
  hosts: all
  become: yes
  vars:
    filetxt: /tmp/text.txt
    startfleet_var: "Contenido para añadir al final del archivo."

  tasks:
    - name: Verificar si el archivo existe
      stat:
        path: "{{ filetxt }}"
      register: fileexist

    - name: Crear archivo si no existe
      file:
        path: "{{ filetxt }}"
        state: touch
      when: not fileexist.stat.exists

    - name: Agregar contenido al archivo
      lineinfile:
        path: "{{ filetxt }}"
        line: "{{ startfleet_var }}"
        insertafter: EOF
        create: yes
    
    - name: Leer contenido del archivo remoto
      ansible.builtin.shell: cat "{{ filetxt }}"
      register: filecontent

    - name: Mostrar contenido del archivo
      ansible.builtin.debug:
        var: filecontent.stdout_lines
