---
- name: Validar y modificar archivo
  hosts: all
  become: true
  vars:
    filetxt: /tmp/text.txt
    startfleet_var: "Contenido para añadir al final del archivo."

  tasks:
    - name: Verificar si el archivo existe
      stat:
        path: "{{ filetxt }}"
      register: fileexist

    - name: Crear archivo si no existe
      file:
        path: "{{ filetxt }}"
        state: touch
      when: not fileexist.stat.exists

    - name: Agregar contenido al archivo
      lineinfile:
        path: "{{ filetxt }}"
        line: "{{ startfleet_var }}"
        create: yes
      when: fileexist.stat.exists

    - name: Leer contenido del archivo remoto
      set_fact:
        remote_file: "{{ lookup('file', '/tmp/text.txt') }}"
      delegate_to: localhost

    - name: Imprimir contenido del archivo remoto
      debug:
        var: remote_file